//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_VoucherBudgetDetail
    {
        public long Id { get; set; }
        public Nullable<long> VoucherBudgetId { get; set; }
        public string CodeUser { get; set; }
        public string NameUser { get; set; }
        public string JobTitle { get; set; }
        public string OrgCompanyName { get; set; }
        public Nullable<int> OrgCompanyId { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatusName { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<int> OrderNo { get; set; }
    }
}
