//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpTransfer
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public System.DateTime TransferDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> OldJobTitleId { get; set; }
        public Nullable<int> NewJobTitleId { get; set; }
        public Nullable<int> OldOrgId { get; set; }
        public Nullable<int> NewOrgId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OldLevel1MngId { get; set; }
        public Nullable<int> NewLevel1MngId { get; set; }
        public Nullable<int> OldLevel2MngId { get; set; }
        public Nullable<int> NewLevel2MngId { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    }
}
