//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kpi_DiaryCriterionDetail
    {
        public int Id { get; set; }
        public int CriterionCatalogId { get; set; }
        public string CriterionCatalogCode { get; set; }
        public string CriterionCatalogName { get; set; }
        public Nullable<int> CriterionCatalogFolderId { get; set; }
        public Nullable<System.DateTime> CriterionDate { get; set; }
        public int CriterionDayOfMonth { get; set; }
        public string UserName { get; set; }
        public string UserFullName { get; set; }
        public int KpiPoint { get; set; }
        public Nullable<int> EventDiaryId { get; set; }
        public int KpiMonthNumber { get; set; }
        public Nullable<int> KpiDayMonthNumber { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedByUser { get; set; }
        public string CreatedByUserFullName { get; set; }
        public string CreatedByUserTitle { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CriterionCatalogNameEn { get; set; }
    }
}
