//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kpi_KpiCriterionDetail
    {
        public int Id { get; set; }
        public int CriterionIndex { get; set; }
        public string CriterionTitle { get; set; }
        public int MinimumPoint { get; set; }
        public int MaximumPoint { get; set; }
        public int EmployeeEvaluatePoint { get; set; }
        public string EmployeeEvaluateComment { get; set; }
        public Nullable<System.DateTime> EmployeeLastUpdatedDate { get; set; }
        public int ManagerEvaluatePoint { get; set; }
        public string ManagerEvaluateComment { get; set; }
        public Nullable<System.DateTime> ManagerLastUpdatedDate { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string UserId { get; set; }
        public Nullable<int> OrgId { get; set; }
        public int KpiEvaluateId { get; set; }
        public int KpiCatalogId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedByUser { get; set; }
    }
}
