//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kpi_CriterionCatalog
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string CriterionTitle { get; set; }
        public int MinimumPoint { get; set; }
        public int MaximumPoint { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool IsFolder { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> CriterionLevel { get; set; }
        public Nullable<bool> IsMinus { get; set; }
        public string CriterionTitleEn { get; set; }
    }
}
