//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kpi_CriterionTypeCatalog
    {
        public int Id { get; set; }
        public Nullable<int> CriterionTypeId { get; set; }
        public Nullable<int> CriterionCatalogId { get; set; }
        public Nullable<int> StartPoint { get; set; }
    }
}
