//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kpi_Task
    {
        public int Id { get; set; }
        public int TaskIndex { get; set; }
        public string Task { get; set; }
        public string Expectation { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Result { get; set; }
        public bool IsFinish { get; set; }
        public int KpiEvaluationId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedByUser { get; set; }
        public string DeadlineStr { get; set; }
    }
}
