//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification_Type
    {
        public int Id { get; set; }
        public Nullable<int> Type { get; set; }
        public string TypeName { get; set; }
        public string ActionName { get; set; }
        public string ObjectName { get; set; }
    }
}
