//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification_Queue
    {
        public int Id { get; set; }
        public Nullable<int> Status { get; set; }
        public string Notes { get; set; }
        public string Action { get; set; }
        public string FromUserName { get; set; }
        public string ToUserName { get; set; }
        public Nullable<System.DateTime> UserDate { get; set; }
        public Nullable<int> Type { get; set; }
        public string NameType { get; set; }
        public string Modules { get; set; }
        public string NotesEn { get; set; }
    }
}
