//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Org_UserOrg
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string UserFullName { get; set; }
        public string UserEmail { get; set; }
        public int OrgId { get; set; }
        public string OrgName { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> JobTitleId { get; set; }
        public Nullable<System.DateTime> FirstKpiDate { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsOrgManager { get; set; }
        public Nullable<int> EventDiaryConfigId { get; set; }
        public Nullable<int> Level1ManagerId { get; set; }
        public Nullable<int> Level2ManagerId { get; set; }
        public string KpiType { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> StartWorkDate { get; set; }
        public Nullable<System.DateTime> EDCUpdateDate { get; set; }
        public string IdCardNumber { get; set; }
        public Nullable<System.DateTime> IdCardDate { get; set; }
        public string IdCardLocation { get; set; }
        public string PhoneNumber { get; set; }
    }
}
