//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Org_Organization
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrganizationTypeID { get; set; }
        public string NodeID { get; set; }
        public string DirectoryPath { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string NameEn { get; set; }
        public Nullable<int> NumberOrder { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
