//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_ProcessStatus
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int BussinessProcessID { get; set; }
        public Nullable<bool> IsFirstProccess { get; set; }
        public Nullable<bool> IsLastProccess { get; set; }
        public string TitleEn { get; set; }
    }
}
