//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_ProcessTransition
    {
        public int ID { get; set; }
        public int SourceProcessID { get; set; }
        public int TargetProcessID { get; set; }
        public int ActionID { get; set; }
        public string ActionName { get; set; }
        public int NumberOfStep { get; set; }
        public int BusinessProcessID { get; set; }
    }
}
