//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_BussinessProcess
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string BusinessDescription { get; set; }
        public string ProcessRequirement { get; set; }
        public string ObjectTypeCode { get; set; }
        public int NumberOfProccess { get; set; }
    }
}
