//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Sequence
    {
        public int Id { get; set; }
        public int OrgId { get; set; }
        public int SequenceNo { get; set; }
        public string Prefix { get; set; }
        public int Step { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
