//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_EventDiaryConfig
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrgId { get; set; }
        public string OrgName { get; set; }
        public string Level1ManagerUserName { get; set; }
        public string Level1ManagerFullName { get; set; }
        public string Level1ManagerJobTitle { get; set; }
        public string Level1ManagerOrgName { get; set; }
        public string Level2ManagerUserName { get; set; }
        public string Level2ManagerFullName { get; set; }
        public string Level2ManagerJobTitle { get; set; }
        public string Level2ManagerOrgName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedByUser { get; set; }
        public bool IsDeleted { get; set; }
        public string Code { get; set; }
        public Nullable<int> Level1ManagerUserId { get; set; }
        public Nullable<int> Level2ManagerUserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
