//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Menu
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public string Text { get; set; }
        public int DisplayOrder { get; set; }
        public Nullable<int> ParrentID { get; set; }
        public string DirectoryPath { get; set; }
        public bool IsDeleted { get; set; }
        public string NameEnglish { get; set; }
    }
}
