//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_UnLockDiaryCriterion
    {
        public long STT { get; set; }
        public string Organization { get; set; }
        public int OrganizationId { get; set; }
        public Nullable<int> YearMonth { get; set; }
        public string DirectoryPath { get; set; }
        public string StatusName { get; set; }
        public string Level1ManagerFullName { get; set; }
        public string Level2ManagerFullName { get; set; }
    }
}
