//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Statistics_Reports
    {
        public long STT { get; set; }
        public Nullable<int> TongSoNhanVien { get; set; }
        public Nullable<int> Tong { get; set; }
        public Nullable<int> AP { get; set; }
        public Nullable<int> A { get; set; }
        public Nullable<int> AM { get; set; }
        public Nullable<int> BP { get; set; }
        public Nullable<int> B { get; set; }
        public Nullable<int> BM { get; set; }
        public Nullable<int> C { get; set; }
        public int OrganizationId { get; set; }
        public string Organization { get; set; }
        public Nullable<int> YearMonth { get; set; }
        public string DirectoryPath { get; set; }
        public Nullable<int> NumberOrder { get; set; }
        public Nullable<int> ParentId { get; set; }
    }
}
