//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_KpiEvaluation_Organization
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public Nullable<int> EventDiaryId { get; set; }
        public string EmployeeName { get; set; }
        public int EmployeeJobId { get; set; }
        public string EmployeeJobTitle { get; set; }
        public string Level1ManagerUserId { get; set; }
        public int Level1ManagerOrgId { get; set; }
        public string Level1ManagerOrgName { get; set; }
        public Nullable<int> Level1ManagerJobTitleId { get; set; }
        public string Level1ManagerJobTitle { get; set; }
        public int StatusId { get; set; }
        public string StatusName { get; set; }
        public System.DateTime KpiMonth { get; set; }
        public int KpiMonthNumber { get; set; }
        public Nullable<int> YearMonth { get; set; }
        public Nullable<int> EmpKpiPoint { get; set; }
        public string EmpKpiClassification { get; set; }
        public Nullable<int> Level1ManagerKpiPoint { get; set; }
        public string Level1ManagerKpiClassification { get; set; }
        public Nullable<int> KpiPeriodConfigId { get; set; }
        public int CriterionType { get; set; }
        public string CriterionTypeName { get; set; }
        public Nullable<int> FinalKpiPoint { get; set; }
        public string FinalKpiClassification { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> ApproveByLevel1Manager { get; set; }
        public string ApproveByLevel1ManagerId { get; set; }
        public Nullable<System.DateTime> ApproveByLevel2Manager { get; set; }
        public string ApproveByLevel2ManagerId { get; set; }
        public string Organization { get; set; }
        public int OrganizationId { get; set; }
        public bool IsDeleted { get; set; }
        public string Level1ManagerUserName { get; set; }
        public string Level1ManagerFullName { get; set; }
        public string Level2ManagerUserName { get; set; }
        public string Level2ManagerFullName { get; set; }
        public string Level2ManagerOrgName { get; set; }
        public string Level2ManagerJobTitle { get; set; }
        public Nullable<System.DateTime> SentHRDate { get; set; }
        public Nullable<int> EventDiaryConfigId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> HrKpiPoint { get; set; }
        public string HrKpiPointClassification { get; set; }
        public string HrKpiPointComment { get; set; }
        public string FinalKpiComment { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string DirectoryPath { get; set; }
        public string Code { get; set; }
        public string reportClassification { get; set; }
        public Nullable<int> reportPoint { get; set; }
        public string SubmitNote { get; set; }
        public string NameEn { get; set; }
        public Nullable<int> NumberOrder { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
