//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kpi.DataAccess.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_EVoucherUser
    {
        public long Id { get; set; }
        public Nullable<long> VoucherCodeId { get; set; }
        public Nullable<long> EvoucheBudgetDetailId { get; set; }
        public string VoucherTypeCode { get; set; }
        public string VoucheTypeName { get; set; }
        public Nullable<decimal> Denominations { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatusName { get; set; }
        public Nullable<System.DateTime> UseDate { get; set; }
        public string Location { get; set; }
        public string CodeUser { get; set; }
        public string NameUser { get; set; }
    }
}
